### ISSUE TITLE
Custom implementation of Wallet just by setting factoryAddress in connector doesn't work

### ISSUE THREAD

**Issue by SahilVasava** [zerodevapp/sdk-v1#19]
SDK is coupled with the account implementation of zerodev sdk specifically GnosisAccount here:
https://github.com/zerodevapp/sdk/blob/ae55d3bc8cf5e34f5bdce10199a1e15bdda6f9a9/packages/sdk/src/GnosisAccountAPI.ts#L123-L131

Throws `UNPREDICTABLE_GAS_LIMIT` error because of that.

**Comment by derekchiang** [comment]
Fixed in #21
